<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DmxConsole.Core\DmxConsole.Core.csproj" />
    <ProjectReference Include="..\DmxConsole.Protocols\DmxConsole.Protocols.csproj" />
    <ProjectReference Include="..\DmxConsole.Fixtures\DmxConsole.Fixtures.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
